Data:
    mode: 'mono'
    image_settings:
        image_channels: ['image', 'peak_time']
    mapping_settings:
        mapping_method:
            'LSTCam': 'bilinear_interpolation'
            'FlashCam': 'bilinear_interpolation'
            'NectarCam': 'bilinear_interpolation'
            'DigiCam': 'bilinear_interpolation'
            'CHEC': 'oversampling'
            'SCTCam': 'oversampling'
            'LSTSiPMCam': 'bilinear_interpolation'
            'MAGICCam': 'bilinear_interpolation'
        padding:
            'LSTCam': 2
            'FlashCam': 2
            'NectarCam': 2
            'DigiCam': 2
            'CHEC': 0
            'SCTCam': 0
            'LSTSiPMCam': 2
            'MAGICCam': 2
Input:
  batch_size_per_worker: 48
  stack_telescope_images: false
  to_pc_options:
    point_cloud: true
    max_points: 600
    relative_coords: true

Model:
  backbone:
    function: get_particle_net
    module: ParticleNet
  head:
    function: standard_head
    module: head
Model Parameters:
  Mask:
    shift: 999.
  EdgeConv:
    convparams:
    - K: 16
      channels:
      - 64
      - 64
      - 64
    - K: 16
      channels:
      - 128
      - 128
      - 128
    - K: 16
      channels:
      - 256
      - 256
      - 256
    - K: 16
      channels:
      - 512
      - 512
      - 512
    pooling: average
    BN: true
    activation: relu
  FinalPool:
    pooling: average
  standard_head:
    type: {fc_head: [512, 256], weight: 1.0}
    energy: {fc_head: [512, 256], weight: 1.0}
    direction: {fc_head: [512, 256], weight: 1.0}
Training:
    validation_split: 0.1
    num_epochs: 10
    verbose: 2
    workers: 1
    optimizer: 'Adam'
    adam_epsilon: 1.0e-8
    base_learning_rate: 0.0001
    lr_reducing_patience: 5
    lr_reducing_factor: 0.5
    lr_reducing_mindelta: 0.01
    lr_reducing_minlr: 0.00001
